// import React from "react";
// import Dashboard from "./dashboard/page";
// function layout() {
//   return (
//     <>
//       <Dashboard />
//       <div>layout</div>
//     </>
//   );
// }

// export default layout;


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AdminNavbar from "@/components/admin/AdminSidebar";
import AdminSidebar from "@/components/admin/AdminSidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Admin Panel Shika Foundation Trust",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar /> */}
        <AdminNavbar />
        {children}
        {/* <Footer /> */}
        <AdminSidebar />
      </body>
    </html>
  );  
}
